kafka:
  boot:
    server: localhost:9092
  topic:
    name: myTopic-kafkasender
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trydb?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: toor12345
  redis:
    host: localhost
    port: 6379